language: C
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq opencl-headers
  - sudo apt-get install cmake
script:
  - mkdir build
  - cd build
  - cmake -G"Unix Makefiles" ../
  - make 
  - make install