language: C
sudo: required
dist: trusty
compiler:
  - gcc
before_install:
  - uname -a
  - sudo apt-get update 
  - sudo apt-get install -y -qq build-essential cmake gfortran 
  - if [ $TRAVIS_OS_NAME = "linux" ]; then
      bash .travis/amd_sdk.sh;
      tar -xjf AMD-SDK.tar.bz2;
      export AMDAPPSDK=${HOME}/AMDAPPSDK;
      export OPENCL_VENDOR_PATH=${AMDAPPSDK}/etc/OpenCL/vendors;
      mkdir -p ${OPENCL_VENDOR_PATH};
      sh AMD-APP-SDK*.sh --tar -xf -C ${AMDAPPSDK};
      echo libamdocl64.so > ${OPENCL_VENDOR_PATH}/amdocl64.icd;
      export LD_LIBRARY_PATH=${AMDAPPSDK}/lib/x86_64:${LD_LIBRARY_PATH};
      chmod +x ${AMDAPPSDK}/bin/x86_64/clinfo;
      ${AMDAPPSDK}/bin/x86_64/clinfo;
    fi;
script:
  - mkdir build
  - cd build
  - cmake -G"Unix Makefiles" ../
  - make hicl hicl_fortran test
  - make install
  - make install -C fortran_interface
  - make install -C test
  - cd ../test
  - ls */*
  - ./bin/hicl_test
  - ./bin/hicl_test_fortran

#notifications:
#  email:
#    recipients:
#      - said.issam@gmail.com
#    on_success: [always|never|change] # default: change
#    on_failure: [always|never|change] # default: always
