language: C
sudo: required
dist: trusty
compiler:
  - gcc
before_install:
  - sudo apt-get update 
  - sudo apt-get install -y -qq build-essential cmake gfortran 
  - if [ $TRAVIS_OS_NAME = "linux" ]; then
      bash .travis/amd_sdk.sh;
      tar -xjf AMD-SDK.tar.bz2;
      export AMDAPPSDK=${HOME}/AMDAPPSDK;
      export OPENCL_VENDOR_PATH=${AMDAPPSDK}/etc/OpenCL/vendors;
      mkdir -p ${OPENCL_VENDOR_PATH};
      sh AMD-APP-SDK*.sh --tar -xf -C ${AMDAPPSDK};
      echo libamdocl64.so > ${OPENCL_VENDOR_PATH}/amdocl64.icd;
      export LD_LIBRARY_PATH=${AMDAPPSDK}/lib/x86_64:${LD_LIBRARY_PATH};
      echo ${LD_LIBRARY_PATH};
      chmod +x ${AMDAPPSDK}/bin/x86_64/clinfo;
      ${AMDAPPSDK}/bin/x86_64/clinfo;
    fi;
script:
  - mkdir build
  - cd build
  - cmake -G"Unix Makefiles" ../
  - make 
  - make install