language: C
sudo: required
dist: trusty
compiler:
  - gcc
before_install:
  - lspci -vvnn | grep VGA
  - fglrxinfo
  - sudo apt-get update 
  - sudo apt-get install fglrx opencl-headers
  - sudo apt-get install cmake
script:
  - mkdir build
  - cd build
  - cmake -G"Unix Makefiles" ../
  - make 
  - make install